-- -------------------------------------------------------------
--
-- Module: filter
-- Generated by MATLAB(R) 9.9 and Filter Design HDL Coder 3.1.8.
-- Generated on: 2021-04-07 14:18:20
-- -------------------------------------------------------------

-- -------------------------------------------------------------
-- HDL Code Generation Options:
--
-- TargetLanguage: VHDL
-- ClockEnableInputPort: ce
-- TargetDirectory: C:\Users\buihu\OneDrive\Máy tính\Stuff\FilterGen
-- SerialPartition: 201
-- TestBenchStimulus: impulse step ramp chirp noise 

-- -------------------------------------------------------------
-- HDL Implementation    : Fully Serial
-- Folding Factor        : 201
-- -------------------------------------------------------------
-- Filter Settings:
--
-- Discrete-Time FIR Filter (real)
-- -------------------------------
-- Filter Structure  : Direct-Form FIR
-- Filter Length     : 201
-- Stable            : Yes
-- Linear Phase      : Yes (Type 1)
-- Arithmetic        : fixed
-- Numerator         : u16,22 -> [0 1.562500e-02)
-- Input             : s16,15 -> [-1 1)
-- Filter Internals  : Full Precision
--   Output          : s39,37 -> [-2 2)  (auto determined)
--   Product         : s32,37 -> [-1.562500e-02 1.562500e-02)  (auto determined)
--   Accumulator     : s39,37 -> [-2 2)  (auto determined)
--   Round Mode      : No rounding
--   Overflow Mode   : No overflow
-- -------------------------------------------------------------



LIBRARY IEEE;
USE IEEE.std_logic_1164.all;
USE IEEE.numeric_std.ALL;

ENTITY filter IS
   PORT( clk                             :   IN    std_logic; 
         ce                              :   IN    std_logic; 
         reset                           :   IN    std_logic; 
         filter_in                       :   IN    std_logic_vector(15 DOWNTO 0); -- sfix16_En15
         filter_out                      :   OUT   std_logic_vector(38 DOWNTO 0)  -- sfix39_En37
         );

END filter;


----------------------------------------------------------------
--Module Architecture: filter
----------------------------------------------------------------
ARCHITECTURE rtl OF filter IS
  -- Local Functions
  -- Type Definitions
  TYPE delay_pipeline_type IS ARRAY (NATURAL range <>) OF signed(15 DOWNTO 0); -- sfix16_En15
  -- Constants
  CONSTANT coeff1                         : unsigned(15 DOWNTO 0) := to_unsigned(854, 16); -- ufix16_En22
  CONSTANT coeff2                         : unsigned(15 DOWNTO 0) := to_unsigned(895, 16); -- ufix16_En22
  CONSTANT coeff3                         : unsigned(15 DOWNTO 0) := to_unsigned(941, 16); -- ufix16_En22
  CONSTANT coeff4                         : unsigned(15 DOWNTO 0) := to_unsigned(994, 16); -- ufix16_En22
  CONSTANT coeff5                         : unsigned(15 DOWNTO 0) := to_unsigned(1054, 16); -- ufix16_En22
  CONSTANT coeff6                         : unsigned(15 DOWNTO 0) := to_unsigned(1121, 16); -- ufix16_En22
  CONSTANT coeff7                         : unsigned(15 DOWNTO 0) := to_unsigned(1197, 16); -- ufix16_En22
  CONSTANT coeff8                         : unsigned(15 DOWNTO 0) := to_unsigned(1281, 16); -- ufix16_En22
  CONSTANT coeff9                         : unsigned(15 DOWNTO 0) := to_unsigned(1375, 16); -- ufix16_En22
  CONSTANT coeff10                        : unsigned(15 DOWNTO 0) := to_unsigned(1479, 16); -- ufix16_En22
  CONSTANT coeff11                        : unsigned(15 DOWNTO 0) := to_unsigned(1594, 16); -- ufix16_En22
  CONSTANT coeff12                        : unsigned(15 DOWNTO 0) := to_unsigned(1720, 16); -- ufix16_En22
  CONSTANT coeff13                        : unsigned(15 DOWNTO 0) := to_unsigned(1858, 16); -- ufix16_En22
  CONSTANT coeff14                        : unsigned(15 DOWNTO 0) := to_unsigned(2008, 16); -- ufix16_En22
  CONSTANT coeff15                        : unsigned(15 DOWNTO 0) := to_unsigned(2171, 16); -- ufix16_En22
  CONSTANT coeff16                        : unsigned(15 DOWNTO 0) := to_unsigned(2348, 16); -- ufix16_En22
  CONSTANT coeff17                        : unsigned(15 DOWNTO 0) := to_unsigned(2538, 16); -- ufix16_En22
  CONSTANT coeff18                        : unsigned(15 DOWNTO 0) := to_unsigned(2743, 16); -- ufix16_En22
  CONSTANT coeff19                        : unsigned(15 DOWNTO 0) := to_unsigned(2963, 16); -- ufix16_En22
  CONSTANT coeff20                        : unsigned(15 DOWNTO 0) := to_unsigned(3198, 16); -- ufix16_En22
  CONSTANT coeff21                        : unsigned(15 DOWNTO 0) := to_unsigned(3448, 16); -- ufix16_En22
  CONSTANT coeff22                        : unsigned(15 DOWNTO 0) := to_unsigned(3715, 16); -- ufix16_En22
  CONSTANT coeff23                        : unsigned(15 DOWNTO 0) := to_unsigned(3997, 16); -- ufix16_En22
  CONSTANT coeff24                        : unsigned(15 DOWNTO 0) := to_unsigned(4297, 16); -- ufix16_En22
  CONSTANT coeff25                        : unsigned(15 DOWNTO 0) := to_unsigned(4613, 16); -- ufix16_En22
  CONSTANT coeff26                        : unsigned(15 DOWNTO 0) := to_unsigned(4946, 16); -- ufix16_En22
  CONSTANT coeff27                        : unsigned(15 DOWNTO 0) := to_unsigned(5296, 16); -- ufix16_En22
  CONSTANT coeff28                        : unsigned(15 DOWNTO 0) := to_unsigned(5664, 16); -- ufix16_En22
  CONSTANT coeff29                        : unsigned(15 DOWNTO 0) := to_unsigned(6049, 16); -- ufix16_En22
  CONSTANT coeff30                        : unsigned(15 DOWNTO 0) := to_unsigned(6452, 16); -- ufix16_En22
  CONSTANT coeff31                        : unsigned(15 DOWNTO 0) := to_unsigned(6872, 16); -- ufix16_En22
  CONSTANT coeff32                        : unsigned(15 DOWNTO 0) := to_unsigned(7310, 16); -- ufix16_En22
  CONSTANT coeff33                        : unsigned(15 DOWNTO 0) := to_unsigned(7765, 16); -- ufix16_En22
  CONSTANT coeff34                        : unsigned(15 DOWNTO 0) := to_unsigned(8238, 16); -- ufix16_En22
  CONSTANT coeff35                        : unsigned(15 DOWNTO 0) := to_unsigned(8728, 16); -- ufix16_En22
  CONSTANT coeff36                        : unsigned(15 DOWNTO 0) := to_unsigned(9236, 16); -- ufix16_En22
  CONSTANT coeff37                        : unsigned(15 DOWNTO 0) := to_unsigned(9760, 16); -- ufix16_En22
  CONSTANT coeff38                        : unsigned(15 DOWNTO 0) := to_unsigned(10301, 16); -- ufix16_En22
  CONSTANT coeff39                        : unsigned(15 DOWNTO 0) := to_unsigned(10858, 16); -- ufix16_En22
  CONSTANT coeff40                        : unsigned(15 DOWNTO 0) := to_unsigned(11431, 16); -- ufix16_En22
  CONSTANT coeff41                        : unsigned(15 DOWNTO 0) := to_unsigned(12020, 16); -- ufix16_En22
  CONSTANT coeff42                        : unsigned(15 DOWNTO 0) := to_unsigned(12624, 16); -- ufix16_En22
  CONSTANT coeff43                        : unsigned(15 DOWNTO 0) := to_unsigned(13243, 16); -- ufix16_En22
  CONSTANT coeff44                        : unsigned(15 DOWNTO 0) := to_unsigned(13876, 16); -- ufix16_En22
  CONSTANT coeff45                        : unsigned(15 DOWNTO 0) := to_unsigned(14523, 16); -- ufix16_En22
  CONSTANT coeff46                        : unsigned(15 DOWNTO 0) := to_unsigned(15183, 16); -- ufix16_En22
  CONSTANT coeff47                        : unsigned(15 DOWNTO 0) := to_unsigned(15855, 16); -- ufix16_En22
  CONSTANT coeff48                        : unsigned(15 DOWNTO 0) := to_unsigned(16539, 16); -- ufix16_En22
  CONSTANT coeff49                        : unsigned(15 DOWNTO 0) := to_unsigned(17235, 16); -- ufix16_En22
  CONSTANT coeff50                        : unsigned(15 DOWNTO 0) := to_unsigned(17941, 16); -- ufix16_En22
  CONSTANT coeff51                        : unsigned(15 DOWNTO 0) := to_unsigned(18656, 16); -- ufix16_En22
  CONSTANT coeff52                        : unsigned(15 DOWNTO 0) := to_unsigned(19381, 16); -- ufix16_En22
  CONSTANT coeff53                        : unsigned(15 DOWNTO 0) := to_unsigned(20113, 16); -- ufix16_En22
  CONSTANT coeff54                        : unsigned(15 DOWNTO 0) := to_unsigned(20852, 16); -- ufix16_En22
  CONSTANT coeff55                        : unsigned(15 DOWNTO 0) := to_unsigned(21598, 16); -- ufix16_En22
  CONSTANT coeff56                        : unsigned(15 DOWNTO 0) := to_unsigned(22350, 16); -- ufix16_En22
  CONSTANT coeff57                        : unsigned(15 DOWNTO 0) := to_unsigned(23105, 16); -- ufix16_En22
  CONSTANT coeff58                        : unsigned(15 DOWNTO 0) := to_unsigned(23864, 16); -- ufix16_En22
  CONSTANT coeff59                        : unsigned(15 DOWNTO 0) := to_unsigned(24626, 16); -- ufix16_En22
  CONSTANT coeff60                        : unsigned(15 DOWNTO 0) := to_unsigned(25389, 16); -- ufix16_En22
  CONSTANT coeff61                        : unsigned(15 DOWNTO 0) := to_unsigned(26153, 16); -- ufix16_En22
  CONSTANT coeff62                        : unsigned(15 DOWNTO 0) := to_unsigned(26916, 16); -- ufix16_En22
  CONSTANT coeff63                        : unsigned(15 DOWNTO 0) := to_unsigned(27678, 16); -- ufix16_En22
  CONSTANT coeff64                        : unsigned(15 DOWNTO 0) := to_unsigned(28437, 16); -- ufix16_En22
  CONSTANT coeff65                        : unsigned(15 DOWNTO 0) := to_unsigned(29192, 16); -- ufix16_En22
  CONSTANT coeff66                        : unsigned(15 DOWNTO 0) := to_unsigned(29943, 16); -- ufix16_En22
  CONSTANT coeff67                        : unsigned(15 DOWNTO 0) := to_unsigned(30687, 16); -- ufix16_En22
  CONSTANT coeff68                        : unsigned(15 DOWNTO 0) := to_unsigned(31425, 16); -- ufix16_En22
  CONSTANT coeff69                        : unsigned(15 DOWNTO 0) := to_unsigned(32155, 16); -- ufix16_En22
  CONSTANT coeff70                        : unsigned(15 DOWNTO 0) := to_unsigned(32876, 16); -- ufix16_En22
  CONSTANT coeff71                        : unsigned(15 DOWNTO 0) := to_unsigned(33586, 16); -- ufix16_En22
  CONSTANT coeff72                        : unsigned(15 DOWNTO 0) := to_unsigned(34286, 16); -- ufix16_En22
  CONSTANT coeff73                        : unsigned(15 DOWNTO 0) := to_unsigned(34973, 16); -- ufix16_En22
  CONSTANT coeff74                        : unsigned(15 DOWNTO 0) := to_unsigned(35647, 16); -- ufix16_En22
  CONSTANT coeff75                        : unsigned(15 DOWNTO 0) := to_unsigned(36306, 16); -- ufix16_En22
  CONSTANT coeff76                        : unsigned(15 DOWNTO 0) := to_unsigned(36951, 16); -- ufix16_En22
  CONSTANT coeff77                        : unsigned(15 DOWNTO 0) := to_unsigned(37579, 16); -- ufix16_En22
  CONSTANT coeff78                        : unsigned(15 DOWNTO 0) := to_unsigned(38189, 16); -- ufix16_En22
  CONSTANT coeff79                        : unsigned(15 DOWNTO 0) := to_unsigned(38781, 16); -- ufix16_En22
  CONSTANT coeff80                        : unsigned(15 DOWNTO 0) := to_unsigned(39354, 16); -- ufix16_En22
  CONSTANT coeff81                        : unsigned(15 DOWNTO 0) := to_unsigned(39907, 16); -- ufix16_En22
  CONSTANT coeff82                        : unsigned(15 DOWNTO 0) := to_unsigned(40439, 16); -- ufix16_En22
  CONSTANT coeff83                        : unsigned(15 DOWNTO 0) := to_unsigned(40949, 16); -- ufix16_En22
  CONSTANT coeff84                        : unsigned(15 DOWNTO 0) := to_unsigned(41437, 16); -- ufix16_En22
  CONSTANT coeff85                        : unsigned(15 DOWNTO 0) := to_unsigned(41901, 16); -- ufix16_En22
  CONSTANT coeff86                        : unsigned(15 DOWNTO 0) := to_unsigned(42341, 16); -- ufix16_En22
  CONSTANT coeff87                        : unsigned(15 DOWNTO 0) := to_unsigned(42755, 16); -- ufix16_En22
  CONSTANT coeff88                        : unsigned(15 DOWNTO 0) := to_unsigned(43145, 16); -- ufix16_En22
  CONSTANT coeff89                        : unsigned(15 DOWNTO 0) := to_unsigned(43508, 16); -- ufix16_En22
  CONSTANT coeff90                        : unsigned(15 DOWNTO 0) := to_unsigned(43844, 16); -- ufix16_En22
  CONSTANT coeff91                        : unsigned(15 DOWNTO 0) := to_unsigned(44153, 16); -- ufix16_En22
  CONSTANT coeff92                        : unsigned(15 DOWNTO 0) := to_unsigned(44434, 16); -- ufix16_En22
  CONSTANT coeff93                        : unsigned(15 DOWNTO 0) := to_unsigned(44687, 16); -- ufix16_En22
  CONSTANT coeff94                        : unsigned(15 DOWNTO 0) := to_unsigned(44911, 16); -- ufix16_En22
  CONSTANT coeff95                        : unsigned(15 DOWNTO 0) := to_unsigned(45106, 16); -- ufix16_En22
  CONSTANT coeff96                        : unsigned(15 DOWNTO 0) := to_unsigned(45271, 16); -- ufix16_En22
  CONSTANT coeff97                        : unsigned(15 DOWNTO 0) := to_unsigned(45407, 16); -- ufix16_En22
  CONSTANT coeff98                        : unsigned(15 DOWNTO 0) := to_unsigned(45513, 16); -- ufix16_En22
  CONSTANT coeff99                        : unsigned(15 DOWNTO 0) := to_unsigned(45588, 16); -- ufix16_En22
  CONSTANT coeff100                       : unsigned(15 DOWNTO 0) := to_unsigned(45634, 16); -- ufix16_En22
  CONSTANT coeff101                       : unsigned(15 DOWNTO 0) := to_unsigned(45649, 16); -- ufix16_En22
  CONSTANT coeff102                       : unsigned(15 DOWNTO 0) := to_unsigned(45634, 16); -- ufix16_En22
  CONSTANT coeff103                       : unsigned(15 DOWNTO 0) := to_unsigned(45588, 16); -- ufix16_En22
  CONSTANT coeff104                       : unsigned(15 DOWNTO 0) := to_unsigned(45513, 16); -- ufix16_En22
  CONSTANT coeff105                       : unsigned(15 DOWNTO 0) := to_unsigned(45407, 16); -- ufix16_En22
  CONSTANT coeff106                       : unsigned(15 DOWNTO 0) := to_unsigned(45271, 16); -- ufix16_En22
  CONSTANT coeff107                       : unsigned(15 DOWNTO 0) := to_unsigned(45106, 16); -- ufix16_En22
  CONSTANT coeff108                       : unsigned(15 DOWNTO 0) := to_unsigned(44911, 16); -- ufix16_En22
  CONSTANT coeff109                       : unsigned(15 DOWNTO 0) := to_unsigned(44687, 16); -- ufix16_En22
  CONSTANT coeff110                       : unsigned(15 DOWNTO 0) := to_unsigned(44434, 16); -- ufix16_En22
  CONSTANT coeff111                       : unsigned(15 DOWNTO 0) := to_unsigned(44153, 16); -- ufix16_En22
  CONSTANT coeff112                       : unsigned(15 DOWNTO 0) := to_unsigned(43844, 16); -- ufix16_En22
  CONSTANT coeff113                       : unsigned(15 DOWNTO 0) := to_unsigned(43508, 16); -- ufix16_En22
  CONSTANT coeff114                       : unsigned(15 DOWNTO 0) := to_unsigned(43145, 16); -- ufix16_En22
  CONSTANT coeff115                       : unsigned(15 DOWNTO 0) := to_unsigned(42755, 16); -- ufix16_En22
  CONSTANT coeff116                       : unsigned(15 DOWNTO 0) := to_unsigned(42341, 16); -- ufix16_En22
  CONSTANT coeff117                       : unsigned(15 DOWNTO 0) := to_unsigned(41901, 16); -- ufix16_En22
  CONSTANT coeff118                       : unsigned(15 DOWNTO 0) := to_unsigned(41437, 16); -- ufix16_En22
  CONSTANT coeff119                       : unsigned(15 DOWNTO 0) := to_unsigned(40949, 16); -- ufix16_En22
  CONSTANT coeff120                       : unsigned(15 DOWNTO 0) := to_unsigned(40439, 16); -- ufix16_En22
  CONSTANT coeff121                       : unsigned(15 DOWNTO 0) := to_unsigned(39907, 16); -- ufix16_En22
  CONSTANT coeff122                       : unsigned(15 DOWNTO 0) := to_unsigned(39354, 16); -- ufix16_En22
  CONSTANT coeff123                       : unsigned(15 DOWNTO 0) := to_unsigned(38781, 16); -- ufix16_En22
  CONSTANT coeff124                       : unsigned(15 DOWNTO 0) := to_unsigned(38189, 16); -- ufix16_En22
  CONSTANT coeff125                       : unsigned(15 DOWNTO 0) := to_unsigned(37579, 16); -- ufix16_En22
  CONSTANT coeff126                       : unsigned(15 DOWNTO 0) := to_unsigned(36951, 16); -- ufix16_En22
  CONSTANT coeff127                       : unsigned(15 DOWNTO 0) := to_unsigned(36306, 16); -- ufix16_En22
  CONSTANT coeff128                       : unsigned(15 DOWNTO 0) := to_unsigned(35647, 16); -- ufix16_En22
  CONSTANT coeff129                       : unsigned(15 DOWNTO 0) := to_unsigned(34973, 16); -- ufix16_En22
  CONSTANT coeff130                       : unsigned(15 DOWNTO 0) := to_unsigned(34286, 16); -- ufix16_En22
  CONSTANT coeff131                       : unsigned(15 DOWNTO 0) := to_unsigned(33586, 16); -- ufix16_En22
  CONSTANT coeff132                       : unsigned(15 DOWNTO 0) := to_unsigned(32876, 16); -- ufix16_En22
  CONSTANT coeff133                       : unsigned(15 DOWNTO 0) := to_unsigned(32155, 16); -- ufix16_En22
  CONSTANT coeff134                       : unsigned(15 DOWNTO 0) := to_unsigned(31425, 16); -- ufix16_En22
  CONSTANT coeff135                       : unsigned(15 DOWNTO 0) := to_unsigned(30687, 16); -- ufix16_En22
  CONSTANT coeff136                       : unsigned(15 DOWNTO 0) := to_unsigned(29943, 16); -- ufix16_En22
  CONSTANT coeff137                       : unsigned(15 DOWNTO 0) := to_unsigned(29192, 16); -- ufix16_En22
  CONSTANT coeff138                       : unsigned(15 DOWNTO 0) := to_unsigned(28437, 16); -- ufix16_En22
  CONSTANT coeff139                       : unsigned(15 DOWNTO 0) := to_unsigned(27678, 16); -- ufix16_En22
  CONSTANT coeff140                       : unsigned(15 DOWNTO 0) := to_unsigned(26916, 16); -- ufix16_En22
  CONSTANT coeff141                       : unsigned(15 DOWNTO 0) := to_unsigned(26153, 16); -- ufix16_En22
  CONSTANT coeff142                       : unsigned(15 DOWNTO 0) := to_unsigned(25389, 16); -- ufix16_En22
  CONSTANT coeff143                       : unsigned(15 DOWNTO 0) := to_unsigned(24626, 16); -- ufix16_En22
  CONSTANT coeff144                       : unsigned(15 DOWNTO 0) := to_unsigned(23864, 16); -- ufix16_En22
  CONSTANT coeff145                       : unsigned(15 DOWNTO 0) := to_unsigned(23105, 16); -- ufix16_En22
  CONSTANT coeff146                       : unsigned(15 DOWNTO 0) := to_unsigned(22350, 16); -- ufix16_En22
  CONSTANT coeff147                       : unsigned(15 DOWNTO 0) := to_unsigned(21598, 16); -- ufix16_En22
  CONSTANT coeff148                       : unsigned(15 DOWNTO 0) := to_unsigned(20852, 16); -- ufix16_En22
  CONSTANT coeff149                       : unsigned(15 DOWNTO 0) := to_unsigned(20113, 16); -- ufix16_En22
  CONSTANT coeff150                       : unsigned(15 DOWNTO 0) := to_unsigned(19381, 16); -- ufix16_En22
  CONSTANT coeff151                       : unsigned(15 DOWNTO 0) := to_unsigned(18656, 16); -- ufix16_En22
  CONSTANT coeff152                       : unsigned(15 DOWNTO 0) := to_unsigned(17941, 16); -- ufix16_En22
  CONSTANT coeff153                       : unsigned(15 DOWNTO 0) := to_unsigned(17235, 16); -- ufix16_En22
  CONSTANT coeff154                       : unsigned(15 DOWNTO 0) := to_unsigned(16539, 16); -- ufix16_En22
  CONSTANT coeff155                       : unsigned(15 DOWNTO 0) := to_unsigned(15855, 16); -- ufix16_En22
  CONSTANT coeff156                       : unsigned(15 DOWNTO 0) := to_unsigned(15183, 16); -- ufix16_En22
  CONSTANT coeff157                       : unsigned(15 DOWNTO 0) := to_unsigned(14523, 16); -- ufix16_En22
  CONSTANT coeff158                       : unsigned(15 DOWNTO 0) := to_unsigned(13876, 16); -- ufix16_En22
  CONSTANT coeff159                       : unsigned(15 DOWNTO 0) := to_unsigned(13243, 16); -- ufix16_En22
  CONSTANT coeff160                       : unsigned(15 DOWNTO 0) := to_unsigned(12624, 16); -- ufix16_En22
  CONSTANT coeff161                       : unsigned(15 DOWNTO 0) := to_unsigned(12020, 16); -- ufix16_En22
  CONSTANT coeff162                       : unsigned(15 DOWNTO 0) := to_unsigned(11431, 16); -- ufix16_En22
  CONSTANT coeff163                       : unsigned(15 DOWNTO 0) := to_unsigned(10858, 16); -- ufix16_En22
  CONSTANT coeff164                       : unsigned(15 DOWNTO 0) := to_unsigned(10301, 16); -- ufix16_En22
  CONSTANT coeff165                       : unsigned(15 DOWNTO 0) := to_unsigned(9760, 16); -- ufix16_En22
  CONSTANT coeff166                       : unsigned(15 DOWNTO 0) := to_unsigned(9236, 16); -- ufix16_En22
  CONSTANT coeff167                       : unsigned(15 DOWNTO 0) := to_unsigned(8728, 16); -- ufix16_En22
  CONSTANT coeff168                       : unsigned(15 DOWNTO 0) := to_unsigned(8238, 16); -- ufix16_En22
  CONSTANT coeff169                       : unsigned(15 DOWNTO 0) := to_unsigned(7765, 16); -- ufix16_En22
  CONSTANT coeff170                       : unsigned(15 DOWNTO 0) := to_unsigned(7310, 16); -- ufix16_En22
  CONSTANT coeff171                       : unsigned(15 DOWNTO 0) := to_unsigned(6872, 16); -- ufix16_En22
  CONSTANT coeff172                       : unsigned(15 DOWNTO 0) := to_unsigned(6452, 16); -- ufix16_En22
  CONSTANT coeff173                       : unsigned(15 DOWNTO 0) := to_unsigned(6049, 16); -- ufix16_En22
  CONSTANT coeff174                       : unsigned(15 DOWNTO 0) := to_unsigned(5664, 16); -- ufix16_En22
  CONSTANT coeff175                       : unsigned(15 DOWNTO 0) := to_unsigned(5296, 16); -- ufix16_En22
  CONSTANT coeff176                       : unsigned(15 DOWNTO 0) := to_unsigned(4946, 16); -- ufix16_En22
  CONSTANT coeff177                       : unsigned(15 DOWNTO 0) := to_unsigned(4613, 16); -- ufix16_En22
  CONSTANT coeff178                       : unsigned(15 DOWNTO 0) := to_unsigned(4297, 16); -- ufix16_En22
  CONSTANT coeff179                       : unsigned(15 DOWNTO 0) := to_unsigned(3997, 16); -- ufix16_En22
  CONSTANT coeff180                       : unsigned(15 DOWNTO 0) := to_unsigned(3715, 16); -- ufix16_En22
  CONSTANT coeff181                       : unsigned(15 DOWNTO 0) := to_unsigned(3448, 16); -- ufix16_En22
  CONSTANT coeff182                       : unsigned(15 DOWNTO 0) := to_unsigned(3198, 16); -- ufix16_En22
  CONSTANT coeff183                       : unsigned(15 DOWNTO 0) := to_unsigned(2963, 16); -- ufix16_En22
  CONSTANT coeff184                       : unsigned(15 DOWNTO 0) := to_unsigned(2743, 16); -- ufix16_En22
  CONSTANT coeff185                       : unsigned(15 DOWNTO 0) := to_unsigned(2538, 16); -- ufix16_En22
  CONSTANT coeff186                       : unsigned(15 DOWNTO 0) := to_unsigned(2348, 16); -- ufix16_En22
  CONSTANT coeff187                       : unsigned(15 DOWNTO 0) := to_unsigned(2171, 16); -- ufix16_En22
  CONSTANT coeff188                       : unsigned(15 DOWNTO 0) := to_unsigned(2008, 16); -- ufix16_En22
  CONSTANT coeff189                       : unsigned(15 DOWNTO 0) := to_unsigned(1858, 16); -- ufix16_En22
  CONSTANT coeff190                       : unsigned(15 DOWNTO 0) := to_unsigned(1720, 16); -- ufix16_En22
  CONSTANT coeff191                       : unsigned(15 DOWNTO 0) := to_unsigned(1594, 16); -- ufix16_En22
  CONSTANT coeff192                       : unsigned(15 DOWNTO 0) := to_unsigned(1479, 16); -- ufix16_En22
  CONSTANT coeff193                       : unsigned(15 DOWNTO 0) := to_unsigned(1375, 16); -- ufix16_En22
  CONSTANT coeff194                       : unsigned(15 DOWNTO 0) := to_unsigned(1281, 16); -- ufix16_En22
  CONSTANT coeff195                       : unsigned(15 DOWNTO 0) := to_unsigned(1197, 16); -- ufix16_En22
  CONSTANT coeff196                       : unsigned(15 DOWNTO 0) := to_unsigned(1121, 16); -- ufix16_En22
  CONSTANT coeff197                       : unsigned(15 DOWNTO 0) := to_unsigned(1054, 16); -- ufix16_En22
  CONSTANT coeff198                       : unsigned(15 DOWNTO 0) := to_unsigned(994, 16); -- ufix16_En22
  CONSTANT coeff199                       : unsigned(15 DOWNTO 0) := to_unsigned(941, 16); -- ufix16_En22
  CONSTANT coeff200                       : unsigned(15 DOWNTO 0) := to_unsigned(895, 16); -- ufix16_En22
  CONSTANT coeff201                       : unsigned(15 DOWNTO 0) := to_unsigned(854, 16); -- ufix16_En22

  -- Signals
  SIGNAL cur_count                        : unsigned(7 DOWNTO 0); -- ufix8
  SIGNAL phase_200                        : std_logic; -- boolean
  SIGNAL phase_0                          : std_logic; -- boolean
  SIGNAL delay_pipeline                   : delay_pipeline_type(0 TO 200); -- sfix16_En15
  SIGNAL inputmux_1                       : signed(15 DOWNTO 0); -- sfix16_En15
  SIGNAL acc_final                        : signed(38 DOWNTO 0); -- sfix39_En37
  SIGNAL acc_out_1                        : signed(38 DOWNTO 0); -- sfix39_En37
  SIGNAL product_1                        : signed(31 DOWNTO 0); -- sfix32_En37
  SIGNAL product_1_mux                    : unsigned(15 DOWNTO 0); -- ufix16_En22
  SIGNAL mul_temp                         : signed(32 DOWNTO 0); -- sfix33_En37
  SIGNAL prod_typeconvert_1               : signed(38 DOWNTO 0); -- sfix39_En37
  SIGNAL acc_sum_1                        : signed(38 DOWNTO 0); -- sfix39_En37
  SIGNAL acc_in_1                         : signed(38 DOWNTO 0); -- sfix39_En37
  SIGNAL add_temp                         : signed(39 DOWNTO 0); -- sfix40_En37
  SIGNAL output_typeconvert               : signed(38 DOWNTO 0); -- sfix39_En37
  SIGNAL output_register                  : signed(38 DOWNTO 0); -- sfix39_En37


BEGIN

  -- Block Statements
  Counter_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      cur_count <= to_unsigned(200, 8);
    ELSIF clk'event AND clk = '1' THEN
      IF ce = '1' THEN
        IF cur_count >= to_unsigned(200, 8) THEN
          cur_count <= to_unsigned(0, 8);
        ELSE
          cur_count <= cur_count + to_unsigned(1, 8);
        END IF;
      END IF;
    END IF; 
  END PROCESS Counter_process;

  phase_200 <= '1' WHEN cur_count = to_unsigned(200, 8) AND ce = '1' ELSE '0';

  phase_0 <= '1' WHEN cur_count = to_unsigned(0, 8) AND ce = '1' ELSE '0';

  Delay_Pipeline_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delay_pipeline(0 TO 200) <= (OTHERS => (OTHERS => '0'));
    ELSIF clk'event AND clk = '1' THEN
      IF phase_200 = '1' THEN
        delay_pipeline(0) <= signed(filter_in);
        delay_pipeline(1 TO 200) <= delay_pipeline(0 TO 199);
      END IF;
    END IF; 
  END PROCESS Delay_Pipeline_process;

  inputmux_1 <= delay_pipeline(0) WHEN ( cur_count = to_unsigned(0, 8) ) ELSE
                     delay_pipeline(1) WHEN ( cur_count = to_unsigned(1, 8) ) ELSE
                     delay_pipeline(2) WHEN ( cur_count = to_unsigned(2, 8) ) ELSE
                     delay_pipeline(3) WHEN ( cur_count = to_unsigned(3, 8) ) ELSE
                     delay_pipeline(4) WHEN ( cur_count = to_unsigned(4, 8) ) ELSE
                     delay_pipeline(5) WHEN ( cur_count = to_unsigned(5, 8) ) ELSE
                     delay_pipeline(6) WHEN ( cur_count = to_unsigned(6, 8) ) ELSE
                     delay_pipeline(7) WHEN ( cur_count = to_unsigned(7, 8) ) ELSE
                     delay_pipeline(8) WHEN ( cur_count = to_unsigned(8, 8) ) ELSE
                     delay_pipeline(9) WHEN ( cur_count = to_unsigned(9, 8) ) ELSE
                     delay_pipeline(10) WHEN ( cur_count = to_unsigned(10, 8) ) ELSE
                     delay_pipeline(11) WHEN ( cur_count = to_unsigned(11, 8) ) ELSE
                     delay_pipeline(12) WHEN ( cur_count = to_unsigned(12, 8) ) ELSE
                     delay_pipeline(13) WHEN ( cur_count = to_unsigned(13, 8) ) ELSE
                     delay_pipeline(14) WHEN ( cur_count = to_unsigned(14, 8) ) ELSE
                     delay_pipeline(15) WHEN ( cur_count = to_unsigned(15, 8) ) ELSE
                     delay_pipeline(16) WHEN ( cur_count = to_unsigned(16, 8) ) ELSE
                     delay_pipeline(17) WHEN ( cur_count = to_unsigned(17, 8) ) ELSE
                     delay_pipeline(18) WHEN ( cur_count = to_unsigned(18, 8) ) ELSE
                     delay_pipeline(19) WHEN ( cur_count = to_unsigned(19, 8) ) ELSE
                     delay_pipeline(20) WHEN ( cur_count = to_unsigned(20, 8) ) ELSE
                     delay_pipeline(21) WHEN ( cur_count = to_unsigned(21, 8) ) ELSE
                     delay_pipeline(22) WHEN ( cur_count = to_unsigned(22, 8) ) ELSE
                     delay_pipeline(23) WHEN ( cur_count = to_unsigned(23, 8) ) ELSE
                     delay_pipeline(24) WHEN ( cur_count = to_unsigned(24, 8) ) ELSE
                     delay_pipeline(25) WHEN ( cur_count = to_unsigned(25, 8) ) ELSE
                     delay_pipeline(26) WHEN ( cur_count = to_unsigned(26, 8) ) ELSE
                     delay_pipeline(27) WHEN ( cur_count = to_unsigned(27, 8) ) ELSE
                     delay_pipeline(28) WHEN ( cur_count = to_unsigned(28, 8) ) ELSE
                     delay_pipeline(29) WHEN ( cur_count = to_unsigned(29, 8) ) ELSE
                     delay_pipeline(30) WHEN ( cur_count = to_unsigned(30, 8) ) ELSE
                     delay_pipeline(31) WHEN ( cur_count = to_unsigned(31, 8) ) ELSE
                     delay_pipeline(32) WHEN ( cur_count = to_unsigned(32, 8) ) ELSE
                     delay_pipeline(33) WHEN ( cur_count = to_unsigned(33, 8) ) ELSE
                     delay_pipeline(34) WHEN ( cur_count = to_unsigned(34, 8) ) ELSE
                     delay_pipeline(35) WHEN ( cur_count = to_unsigned(35, 8) ) ELSE
                     delay_pipeline(36) WHEN ( cur_count = to_unsigned(36, 8) ) ELSE
                     delay_pipeline(37) WHEN ( cur_count = to_unsigned(37, 8) ) ELSE
                     delay_pipeline(38) WHEN ( cur_count = to_unsigned(38, 8) ) ELSE
                     delay_pipeline(39) WHEN ( cur_count = to_unsigned(39, 8) ) ELSE
                     delay_pipeline(40) WHEN ( cur_count = to_unsigned(40, 8) ) ELSE
                     delay_pipeline(41) WHEN ( cur_count = to_unsigned(41, 8) ) ELSE
                     delay_pipeline(42) WHEN ( cur_count = to_unsigned(42, 8) ) ELSE
                     delay_pipeline(43) WHEN ( cur_count = to_unsigned(43, 8) ) ELSE
                     delay_pipeline(44) WHEN ( cur_count = to_unsigned(44, 8) ) ELSE
                     delay_pipeline(45) WHEN ( cur_count = to_unsigned(45, 8) ) ELSE
                     delay_pipeline(46) WHEN ( cur_count = to_unsigned(46, 8) ) ELSE
                     delay_pipeline(47) WHEN ( cur_count = to_unsigned(47, 8) ) ELSE
                     delay_pipeline(48) WHEN ( cur_count = to_unsigned(48, 8) ) ELSE
                     delay_pipeline(49) WHEN ( cur_count = to_unsigned(49, 8) ) ELSE
                     delay_pipeline(50) WHEN ( cur_count = to_unsigned(50, 8) ) ELSE
                     delay_pipeline(51) WHEN ( cur_count = to_unsigned(51, 8) ) ELSE
                     delay_pipeline(52) WHEN ( cur_count = to_unsigned(52, 8) ) ELSE
                     delay_pipeline(53) WHEN ( cur_count = to_unsigned(53, 8) ) ELSE
                     delay_pipeline(54) WHEN ( cur_count = to_unsigned(54, 8) ) ELSE
                     delay_pipeline(55) WHEN ( cur_count = to_unsigned(55, 8) ) ELSE
                     delay_pipeline(56) WHEN ( cur_count = to_unsigned(56, 8) ) ELSE
                     delay_pipeline(57) WHEN ( cur_count = to_unsigned(57, 8) ) ELSE
                     delay_pipeline(58) WHEN ( cur_count = to_unsigned(58, 8) ) ELSE
                     delay_pipeline(59) WHEN ( cur_count = to_unsigned(59, 8) ) ELSE
                     delay_pipeline(60) WHEN ( cur_count = to_unsigned(60, 8) ) ELSE
                     delay_pipeline(61) WHEN ( cur_count = to_unsigned(61, 8) ) ELSE
                     delay_pipeline(62) WHEN ( cur_count = to_unsigned(62, 8) ) ELSE
                     delay_pipeline(63) WHEN ( cur_count = to_unsigned(63, 8) ) ELSE
                     delay_pipeline(64) WHEN ( cur_count = to_unsigned(64, 8) ) ELSE
                     delay_pipeline(65) WHEN ( cur_count = to_unsigned(65, 8) ) ELSE
                     delay_pipeline(66) WHEN ( cur_count = to_unsigned(66, 8) ) ELSE
                     delay_pipeline(67) WHEN ( cur_count = to_unsigned(67, 8) ) ELSE
                     delay_pipeline(68) WHEN ( cur_count = to_unsigned(68, 8) ) ELSE
                     delay_pipeline(69) WHEN ( cur_count = to_unsigned(69, 8) ) ELSE
                     delay_pipeline(70) WHEN ( cur_count = to_unsigned(70, 8) ) ELSE
                     delay_pipeline(71) WHEN ( cur_count = to_unsigned(71, 8) ) ELSE
                     delay_pipeline(72) WHEN ( cur_count = to_unsigned(72, 8) ) ELSE
                     delay_pipeline(73) WHEN ( cur_count = to_unsigned(73, 8) ) ELSE
                     delay_pipeline(74) WHEN ( cur_count = to_unsigned(74, 8) ) ELSE
                     delay_pipeline(75) WHEN ( cur_count = to_unsigned(75, 8) ) ELSE
                     delay_pipeline(76) WHEN ( cur_count = to_unsigned(76, 8) ) ELSE
                     delay_pipeline(77) WHEN ( cur_count = to_unsigned(77, 8) ) ELSE
                     delay_pipeline(78) WHEN ( cur_count = to_unsigned(78, 8) ) ELSE
                     delay_pipeline(79) WHEN ( cur_count = to_unsigned(79, 8) ) ELSE
                     delay_pipeline(80) WHEN ( cur_count = to_unsigned(80, 8) ) ELSE
                     delay_pipeline(81) WHEN ( cur_count = to_unsigned(81, 8) ) ELSE
                     delay_pipeline(82) WHEN ( cur_count = to_unsigned(82, 8) ) ELSE
                     delay_pipeline(83) WHEN ( cur_count = to_unsigned(83, 8) ) ELSE
                     delay_pipeline(84) WHEN ( cur_count = to_unsigned(84, 8) ) ELSE
                     delay_pipeline(85) WHEN ( cur_count = to_unsigned(85, 8) ) ELSE
                     delay_pipeline(86) WHEN ( cur_count = to_unsigned(86, 8) ) ELSE
                     delay_pipeline(87) WHEN ( cur_count = to_unsigned(87, 8) ) ELSE
                     delay_pipeline(88) WHEN ( cur_count = to_unsigned(88, 8) ) ELSE
                     delay_pipeline(89) WHEN ( cur_count = to_unsigned(89, 8) ) ELSE
                     delay_pipeline(90) WHEN ( cur_count = to_unsigned(90, 8) ) ELSE
                     delay_pipeline(91) WHEN ( cur_count = to_unsigned(91, 8) ) ELSE
                     delay_pipeline(92) WHEN ( cur_count = to_unsigned(92, 8) ) ELSE
                     delay_pipeline(93) WHEN ( cur_count = to_unsigned(93, 8) ) ELSE
                     delay_pipeline(94) WHEN ( cur_count = to_unsigned(94, 8) ) ELSE
                     delay_pipeline(95) WHEN ( cur_count = to_unsigned(95, 8) ) ELSE
                     delay_pipeline(96) WHEN ( cur_count = to_unsigned(96, 8) ) ELSE
                     delay_pipeline(97) WHEN ( cur_count = to_unsigned(97, 8) ) ELSE
                     delay_pipeline(98) WHEN ( cur_count = to_unsigned(98, 8) ) ELSE
                     delay_pipeline(99) WHEN ( cur_count = to_unsigned(99, 8) ) ELSE
                     delay_pipeline(100) WHEN ( cur_count = to_unsigned(100, 8) ) ELSE
                     delay_pipeline(101) WHEN ( cur_count = to_unsigned(101, 8) ) ELSE
                     delay_pipeline(102) WHEN ( cur_count = to_unsigned(102, 8) ) ELSE
                     delay_pipeline(103) WHEN ( cur_count = to_unsigned(103, 8) ) ELSE
                     delay_pipeline(104) WHEN ( cur_count = to_unsigned(104, 8) ) ELSE
                     delay_pipeline(105) WHEN ( cur_count = to_unsigned(105, 8) ) ELSE
                     delay_pipeline(106) WHEN ( cur_count = to_unsigned(106, 8) ) ELSE
                     delay_pipeline(107) WHEN ( cur_count = to_unsigned(107, 8) ) ELSE
                     delay_pipeline(108) WHEN ( cur_count = to_unsigned(108, 8) ) ELSE
                     delay_pipeline(109) WHEN ( cur_count = to_unsigned(109, 8) ) ELSE
                     delay_pipeline(110) WHEN ( cur_count = to_unsigned(110, 8) ) ELSE
                     delay_pipeline(111) WHEN ( cur_count = to_unsigned(111, 8) ) ELSE
                     delay_pipeline(112) WHEN ( cur_count = to_unsigned(112, 8) ) ELSE
                     delay_pipeline(113) WHEN ( cur_count = to_unsigned(113, 8) ) ELSE
                     delay_pipeline(114) WHEN ( cur_count = to_unsigned(114, 8) ) ELSE
                     delay_pipeline(115) WHEN ( cur_count = to_unsigned(115, 8) ) ELSE
                     delay_pipeline(116) WHEN ( cur_count = to_unsigned(116, 8) ) ELSE
                     delay_pipeline(117) WHEN ( cur_count = to_unsigned(117, 8) ) ELSE
                     delay_pipeline(118) WHEN ( cur_count = to_unsigned(118, 8) ) ELSE
                     delay_pipeline(119) WHEN ( cur_count = to_unsigned(119, 8) ) ELSE
                     delay_pipeline(120) WHEN ( cur_count = to_unsigned(120, 8) ) ELSE
                     delay_pipeline(121) WHEN ( cur_count = to_unsigned(121, 8) ) ELSE
                     delay_pipeline(122) WHEN ( cur_count = to_unsigned(122, 8) ) ELSE
                     delay_pipeline(123) WHEN ( cur_count = to_unsigned(123, 8) ) ELSE
                     delay_pipeline(124) WHEN ( cur_count = to_unsigned(124, 8) ) ELSE
                     delay_pipeline(125) WHEN ( cur_count = to_unsigned(125, 8) ) ELSE
                     delay_pipeline(126) WHEN ( cur_count = to_unsigned(126, 8) ) ELSE
                     delay_pipeline(127) WHEN ( cur_count = to_unsigned(127, 8) ) ELSE
                     delay_pipeline(128) WHEN ( cur_count = to_unsigned(128, 8) ) ELSE
                     delay_pipeline(129) WHEN ( cur_count = to_unsigned(129, 8) ) ELSE
                     delay_pipeline(130) WHEN ( cur_count = to_unsigned(130, 8) ) ELSE
                     delay_pipeline(131) WHEN ( cur_count = to_unsigned(131, 8) ) ELSE
                     delay_pipeline(132) WHEN ( cur_count = to_unsigned(132, 8) ) ELSE
                     delay_pipeline(133) WHEN ( cur_count = to_unsigned(133, 8) ) ELSE
                     delay_pipeline(134) WHEN ( cur_count = to_unsigned(134, 8) ) ELSE
                     delay_pipeline(135) WHEN ( cur_count = to_unsigned(135, 8) ) ELSE
                     delay_pipeline(136) WHEN ( cur_count = to_unsigned(136, 8) ) ELSE
                     delay_pipeline(137) WHEN ( cur_count = to_unsigned(137, 8) ) ELSE
                     delay_pipeline(138) WHEN ( cur_count = to_unsigned(138, 8) ) ELSE
                     delay_pipeline(139) WHEN ( cur_count = to_unsigned(139, 8) ) ELSE
                     delay_pipeline(140) WHEN ( cur_count = to_unsigned(140, 8) ) ELSE
                     delay_pipeline(141) WHEN ( cur_count = to_unsigned(141, 8) ) ELSE
                     delay_pipeline(142) WHEN ( cur_count = to_unsigned(142, 8) ) ELSE
                     delay_pipeline(143) WHEN ( cur_count = to_unsigned(143, 8) ) ELSE
                     delay_pipeline(144) WHEN ( cur_count = to_unsigned(144, 8) ) ELSE
                     delay_pipeline(145) WHEN ( cur_count = to_unsigned(145, 8) ) ELSE
                     delay_pipeline(146) WHEN ( cur_count = to_unsigned(146, 8) ) ELSE
                     delay_pipeline(147) WHEN ( cur_count = to_unsigned(147, 8) ) ELSE
                     delay_pipeline(148) WHEN ( cur_count = to_unsigned(148, 8) ) ELSE
                     delay_pipeline(149) WHEN ( cur_count = to_unsigned(149, 8) ) ELSE
                     delay_pipeline(150) WHEN ( cur_count = to_unsigned(150, 8) ) ELSE
                     delay_pipeline(151) WHEN ( cur_count = to_unsigned(151, 8) ) ELSE
                     delay_pipeline(152) WHEN ( cur_count = to_unsigned(152, 8) ) ELSE
                     delay_pipeline(153) WHEN ( cur_count = to_unsigned(153, 8) ) ELSE
                     delay_pipeline(154) WHEN ( cur_count = to_unsigned(154, 8) ) ELSE
                     delay_pipeline(155) WHEN ( cur_count = to_unsigned(155, 8) ) ELSE
                     delay_pipeline(156) WHEN ( cur_count = to_unsigned(156, 8) ) ELSE
                     delay_pipeline(157) WHEN ( cur_count = to_unsigned(157, 8) ) ELSE
                     delay_pipeline(158) WHEN ( cur_count = to_unsigned(158, 8) ) ELSE
                     delay_pipeline(159) WHEN ( cur_count = to_unsigned(159, 8) ) ELSE
                     delay_pipeline(160) WHEN ( cur_count = to_unsigned(160, 8) ) ELSE
                     delay_pipeline(161) WHEN ( cur_count = to_unsigned(161, 8) ) ELSE
                     delay_pipeline(162) WHEN ( cur_count = to_unsigned(162, 8) ) ELSE
                     delay_pipeline(163) WHEN ( cur_count = to_unsigned(163, 8) ) ELSE
                     delay_pipeline(164) WHEN ( cur_count = to_unsigned(164, 8) ) ELSE
                     delay_pipeline(165) WHEN ( cur_count = to_unsigned(165, 8) ) ELSE
                     delay_pipeline(166) WHEN ( cur_count = to_unsigned(166, 8) ) ELSE
                     delay_pipeline(167) WHEN ( cur_count = to_unsigned(167, 8) ) ELSE
                     delay_pipeline(168) WHEN ( cur_count = to_unsigned(168, 8) ) ELSE
                     delay_pipeline(169) WHEN ( cur_count = to_unsigned(169, 8) ) ELSE
                     delay_pipeline(170) WHEN ( cur_count = to_unsigned(170, 8) ) ELSE
                     delay_pipeline(171) WHEN ( cur_count = to_unsigned(171, 8) ) ELSE
                     delay_pipeline(172) WHEN ( cur_count = to_unsigned(172, 8) ) ELSE
                     delay_pipeline(173) WHEN ( cur_count = to_unsigned(173, 8) ) ELSE
                     delay_pipeline(174) WHEN ( cur_count = to_unsigned(174, 8) ) ELSE
                     delay_pipeline(175) WHEN ( cur_count = to_unsigned(175, 8) ) ELSE
                     delay_pipeline(176) WHEN ( cur_count = to_unsigned(176, 8) ) ELSE
                     delay_pipeline(177) WHEN ( cur_count = to_unsigned(177, 8) ) ELSE
                     delay_pipeline(178) WHEN ( cur_count = to_unsigned(178, 8) ) ELSE
                     delay_pipeline(179) WHEN ( cur_count = to_unsigned(179, 8) ) ELSE
                     delay_pipeline(180) WHEN ( cur_count = to_unsigned(180, 8) ) ELSE
                     delay_pipeline(181) WHEN ( cur_count = to_unsigned(181, 8) ) ELSE
                     delay_pipeline(182) WHEN ( cur_count = to_unsigned(182, 8) ) ELSE
                     delay_pipeline(183) WHEN ( cur_count = to_unsigned(183, 8) ) ELSE
                     delay_pipeline(184) WHEN ( cur_count = to_unsigned(184, 8) ) ELSE
                     delay_pipeline(185) WHEN ( cur_count = to_unsigned(185, 8) ) ELSE
                     delay_pipeline(186) WHEN ( cur_count = to_unsigned(186, 8) ) ELSE
                     delay_pipeline(187) WHEN ( cur_count = to_unsigned(187, 8) ) ELSE
                     delay_pipeline(188) WHEN ( cur_count = to_unsigned(188, 8) ) ELSE
                     delay_pipeline(189) WHEN ( cur_count = to_unsigned(189, 8) ) ELSE
                     delay_pipeline(190) WHEN ( cur_count = to_unsigned(190, 8) ) ELSE
                     delay_pipeline(191) WHEN ( cur_count = to_unsigned(191, 8) ) ELSE
                     delay_pipeline(192) WHEN ( cur_count = to_unsigned(192, 8) ) ELSE
                     delay_pipeline(193) WHEN ( cur_count = to_unsigned(193, 8) ) ELSE
                     delay_pipeline(194) WHEN ( cur_count = to_unsigned(194, 8) ) ELSE
                     delay_pipeline(195) WHEN ( cur_count = to_unsigned(195, 8) ) ELSE
                     delay_pipeline(196) WHEN ( cur_count = to_unsigned(196, 8) ) ELSE
                     delay_pipeline(197) WHEN ( cur_count = to_unsigned(197, 8) ) ELSE
                     delay_pipeline(198) WHEN ( cur_count = to_unsigned(198, 8) ) ELSE
                     delay_pipeline(199) WHEN ( cur_count = to_unsigned(199, 8) ) ELSE
                     delay_pipeline(200);

  --   ------------------ Serial partition # 1 ------------------

  product_1_mux <= coeff1 WHEN ( cur_count = to_unsigned(0, 8) ) ELSE
                        coeff2 WHEN ( cur_count = to_unsigned(1, 8) ) ELSE
                        coeff3 WHEN ( cur_count = to_unsigned(2, 8) ) ELSE
                        coeff4 WHEN ( cur_count = to_unsigned(3, 8) ) ELSE
                        coeff5 WHEN ( cur_count = to_unsigned(4, 8) ) ELSE
                        coeff6 WHEN ( cur_count = to_unsigned(5, 8) ) ELSE
                        coeff7 WHEN ( cur_count = to_unsigned(6, 8) ) ELSE
                        coeff8 WHEN ( cur_count = to_unsigned(7, 8) ) ELSE
                        coeff9 WHEN ( cur_count = to_unsigned(8, 8) ) ELSE
                        coeff10 WHEN ( cur_count = to_unsigned(9, 8) ) ELSE
                        coeff11 WHEN ( cur_count = to_unsigned(10, 8) ) ELSE
                        coeff12 WHEN ( cur_count = to_unsigned(11, 8) ) ELSE
                        coeff13 WHEN ( cur_count = to_unsigned(12, 8) ) ELSE
                        coeff14 WHEN ( cur_count = to_unsigned(13, 8) ) ELSE
                        coeff15 WHEN ( cur_count = to_unsigned(14, 8) ) ELSE
                        coeff16 WHEN ( cur_count = to_unsigned(15, 8) ) ELSE
                        coeff17 WHEN ( cur_count = to_unsigned(16, 8) ) ELSE
                        coeff18 WHEN ( cur_count = to_unsigned(17, 8) ) ELSE
                        coeff19 WHEN ( cur_count = to_unsigned(18, 8) ) ELSE
                        coeff20 WHEN ( cur_count = to_unsigned(19, 8) ) ELSE
                        coeff21 WHEN ( cur_count = to_unsigned(20, 8) ) ELSE
                        coeff22 WHEN ( cur_count = to_unsigned(21, 8) ) ELSE
                        coeff23 WHEN ( cur_count = to_unsigned(22, 8) ) ELSE
                        coeff24 WHEN ( cur_count = to_unsigned(23, 8) ) ELSE
                        coeff25 WHEN ( cur_count = to_unsigned(24, 8) ) ELSE
                        coeff26 WHEN ( cur_count = to_unsigned(25, 8) ) ELSE
                        coeff27 WHEN ( cur_count = to_unsigned(26, 8) ) ELSE
                        coeff28 WHEN ( cur_count = to_unsigned(27, 8) ) ELSE
                        coeff29 WHEN ( cur_count = to_unsigned(28, 8) ) ELSE
                        coeff30 WHEN ( cur_count = to_unsigned(29, 8) ) ELSE
                        coeff31 WHEN ( cur_count = to_unsigned(30, 8) ) ELSE
                        coeff32 WHEN ( cur_count = to_unsigned(31, 8) ) ELSE
                        coeff33 WHEN ( cur_count = to_unsigned(32, 8) ) ELSE
                        coeff34 WHEN ( cur_count = to_unsigned(33, 8) ) ELSE
                        coeff35 WHEN ( cur_count = to_unsigned(34, 8) ) ELSE
                        coeff36 WHEN ( cur_count = to_unsigned(35, 8) ) ELSE
                        coeff37 WHEN ( cur_count = to_unsigned(36, 8) ) ELSE
                        coeff38 WHEN ( cur_count = to_unsigned(37, 8) ) ELSE
                        coeff39 WHEN ( cur_count = to_unsigned(38, 8) ) ELSE
                        coeff40 WHEN ( cur_count = to_unsigned(39, 8) ) ELSE
                        coeff41 WHEN ( cur_count = to_unsigned(40, 8) ) ELSE
                        coeff42 WHEN ( cur_count = to_unsigned(41, 8) ) ELSE
                        coeff43 WHEN ( cur_count = to_unsigned(42, 8) ) ELSE
                        coeff44 WHEN ( cur_count = to_unsigned(43, 8) ) ELSE
                        coeff45 WHEN ( cur_count = to_unsigned(44, 8) ) ELSE
                        coeff46 WHEN ( cur_count = to_unsigned(45, 8) ) ELSE
                        coeff47 WHEN ( cur_count = to_unsigned(46, 8) ) ELSE
                        coeff48 WHEN ( cur_count = to_unsigned(47, 8) ) ELSE
                        coeff49 WHEN ( cur_count = to_unsigned(48, 8) ) ELSE
                        coeff50 WHEN ( cur_count = to_unsigned(49, 8) ) ELSE
                        coeff51 WHEN ( cur_count = to_unsigned(50, 8) ) ELSE
                        coeff52 WHEN ( cur_count = to_unsigned(51, 8) ) ELSE
                        coeff53 WHEN ( cur_count = to_unsigned(52, 8) ) ELSE
                        coeff54 WHEN ( cur_count = to_unsigned(53, 8) ) ELSE
                        coeff55 WHEN ( cur_count = to_unsigned(54, 8) ) ELSE
                        coeff56 WHEN ( cur_count = to_unsigned(55, 8) ) ELSE
                        coeff57 WHEN ( cur_count = to_unsigned(56, 8) ) ELSE
                        coeff58 WHEN ( cur_count = to_unsigned(57, 8) ) ELSE
                        coeff59 WHEN ( cur_count = to_unsigned(58, 8) ) ELSE
                        coeff60 WHEN ( cur_count = to_unsigned(59, 8) ) ELSE
                        coeff61 WHEN ( cur_count = to_unsigned(60, 8) ) ELSE
                        coeff62 WHEN ( cur_count = to_unsigned(61, 8) ) ELSE
                        coeff63 WHEN ( cur_count = to_unsigned(62, 8) ) ELSE
                        coeff64 WHEN ( cur_count = to_unsigned(63, 8) ) ELSE
                        coeff65 WHEN ( cur_count = to_unsigned(64, 8) ) ELSE
                        coeff66 WHEN ( cur_count = to_unsigned(65, 8) ) ELSE
                        coeff67 WHEN ( cur_count = to_unsigned(66, 8) ) ELSE
                        coeff68 WHEN ( cur_count = to_unsigned(67, 8) ) ELSE
                        coeff69 WHEN ( cur_count = to_unsigned(68, 8) ) ELSE
                        coeff70 WHEN ( cur_count = to_unsigned(69, 8) ) ELSE
                        coeff71 WHEN ( cur_count = to_unsigned(70, 8) ) ELSE
                        coeff72 WHEN ( cur_count = to_unsigned(71, 8) ) ELSE
                        coeff73 WHEN ( cur_count = to_unsigned(72, 8) ) ELSE
                        coeff74 WHEN ( cur_count = to_unsigned(73, 8) ) ELSE
                        coeff75 WHEN ( cur_count = to_unsigned(74, 8) ) ELSE
                        coeff76 WHEN ( cur_count = to_unsigned(75, 8) ) ELSE
                        coeff77 WHEN ( cur_count = to_unsigned(76, 8) ) ELSE
                        coeff78 WHEN ( cur_count = to_unsigned(77, 8) ) ELSE
                        coeff79 WHEN ( cur_count = to_unsigned(78, 8) ) ELSE
                        coeff80 WHEN ( cur_count = to_unsigned(79, 8) ) ELSE
                        coeff81 WHEN ( cur_count = to_unsigned(80, 8) ) ELSE
                        coeff82 WHEN ( cur_count = to_unsigned(81, 8) ) ELSE
                        coeff83 WHEN ( cur_count = to_unsigned(82, 8) ) ELSE
                        coeff84 WHEN ( cur_count = to_unsigned(83, 8) ) ELSE
                        coeff85 WHEN ( cur_count = to_unsigned(84, 8) ) ELSE
                        coeff86 WHEN ( cur_count = to_unsigned(85, 8) ) ELSE
                        coeff87 WHEN ( cur_count = to_unsigned(86, 8) ) ELSE
                        coeff88 WHEN ( cur_count = to_unsigned(87, 8) ) ELSE
                        coeff89 WHEN ( cur_count = to_unsigned(88, 8) ) ELSE
                        coeff90 WHEN ( cur_count = to_unsigned(89, 8) ) ELSE
                        coeff91 WHEN ( cur_count = to_unsigned(90, 8) ) ELSE
                        coeff92 WHEN ( cur_count = to_unsigned(91, 8) ) ELSE
                        coeff93 WHEN ( cur_count = to_unsigned(92, 8) ) ELSE
                        coeff94 WHEN ( cur_count = to_unsigned(93, 8) ) ELSE
                        coeff95 WHEN ( cur_count = to_unsigned(94, 8) ) ELSE
                        coeff96 WHEN ( cur_count = to_unsigned(95, 8) ) ELSE
                        coeff97 WHEN ( cur_count = to_unsigned(96, 8) ) ELSE
                        coeff98 WHEN ( cur_count = to_unsigned(97, 8) ) ELSE
                        coeff99 WHEN ( cur_count = to_unsigned(98, 8) ) ELSE
                        coeff100 WHEN ( cur_count = to_unsigned(99, 8) ) ELSE
                        coeff101 WHEN ( cur_count = to_unsigned(100, 8) ) ELSE
                        coeff102 WHEN ( cur_count = to_unsigned(101, 8) ) ELSE
                        coeff103 WHEN ( cur_count = to_unsigned(102, 8) ) ELSE
                        coeff104 WHEN ( cur_count = to_unsigned(103, 8) ) ELSE
                        coeff105 WHEN ( cur_count = to_unsigned(104, 8) ) ELSE
                        coeff106 WHEN ( cur_count = to_unsigned(105, 8) ) ELSE
                        coeff107 WHEN ( cur_count = to_unsigned(106, 8) ) ELSE
                        coeff108 WHEN ( cur_count = to_unsigned(107, 8) ) ELSE
                        coeff109 WHEN ( cur_count = to_unsigned(108, 8) ) ELSE
                        coeff110 WHEN ( cur_count = to_unsigned(109, 8) ) ELSE
                        coeff111 WHEN ( cur_count = to_unsigned(110, 8) ) ELSE
                        coeff112 WHEN ( cur_count = to_unsigned(111, 8) ) ELSE
                        coeff113 WHEN ( cur_count = to_unsigned(112, 8) ) ELSE
                        coeff114 WHEN ( cur_count = to_unsigned(113, 8) ) ELSE
                        coeff115 WHEN ( cur_count = to_unsigned(114, 8) ) ELSE
                        coeff116 WHEN ( cur_count = to_unsigned(115, 8) ) ELSE
                        coeff117 WHEN ( cur_count = to_unsigned(116, 8) ) ELSE
                        coeff118 WHEN ( cur_count = to_unsigned(117, 8) ) ELSE
                        coeff119 WHEN ( cur_count = to_unsigned(118, 8) ) ELSE
                        coeff120 WHEN ( cur_count = to_unsigned(119, 8) ) ELSE
                        coeff121 WHEN ( cur_count = to_unsigned(120, 8) ) ELSE
                        coeff122 WHEN ( cur_count = to_unsigned(121, 8) ) ELSE
                        coeff123 WHEN ( cur_count = to_unsigned(122, 8) ) ELSE
                        coeff124 WHEN ( cur_count = to_unsigned(123, 8) ) ELSE
                        coeff125 WHEN ( cur_count = to_unsigned(124, 8) ) ELSE
                        coeff126 WHEN ( cur_count = to_unsigned(125, 8) ) ELSE
                        coeff127 WHEN ( cur_count = to_unsigned(126, 8) ) ELSE
                        coeff128 WHEN ( cur_count = to_unsigned(127, 8) ) ELSE
                        coeff129 WHEN ( cur_count = to_unsigned(128, 8) ) ELSE
                        coeff130 WHEN ( cur_count = to_unsigned(129, 8) ) ELSE
                        coeff131 WHEN ( cur_count = to_unsigned(130, 8) ) ELSE
                        coeff132 WHEN ( cur_count = to_unsigned(131, 8) ) ELSE
                        coeff133 WHEN ( cur_count = to_unsigned(132, 8) ) ELSE
                        coeff134 WHEN ( cur_count = to_unsigned(133, 8) ) ELSE
                        coeff135 WHEN ( cur_count = to_unsigned(134, 8) ) ELSE
                        coeff136 WHEN ( cur_count = to_unsigned(135, 8) ) ELSE
                        coeff137 WHEN ( cur_count = to_unsigned(136, 8) ) ELSE
                        coeff138 WHEN ( cur_count = to_unsigned(137, 8) ) ELSE
                        coeff139 WHEN ( cur_count = to_unsigned(138, 8) ) ELSE
                        coeff140 WHEN ( cur_count = to_unsigned(139, 8) ) ELSE
                        coeff141 WHEN ( cur_count = to_unsigned(140, 8) ) ELSE
                        coeff142 WHEN ( cur_count = to_unsigned(141, 8) ) ELSE
                        coeff143 WHEN ( cur_count = to_unsigned(142, 8) ) ELSE
                        coeff144 WHEN ( cur_count = to_unsigned(143, 8) ) ELSE
                        coeff145 WHEN ( cur_count = to_unsigned(144, 8) ) ELSE
                        coeff146 WHEN ( cur_count = to_unsigned(145, 8) ) ELSE
                        coeff147 WHEN ( cur_count = to_unsigned(146, 8) ) ELSE
                        coeff148 WHEN ( cur_count = to_unsigned(147, 8) ) ELSE
                        coeff149 WHEN ( cur_count = to_unsigned(148, 8) ) ELSE
                        coeff150 WHEN ( cur_count = to_unsigned(149, 8) ) ELSE
                        coeff151 WHEN ( cur_count = to_unsigned(150, 8) ) ELSE
                        coeff152 WHEN ( cur_count = to_unsigned(151, 8) ) ELSE
                        coeff153 WHEN ( cur_count = to_unsigned(152, 8) ) ELSE
                        coeff154 WHEN ( cur_count = to_unsigned(153, 8) ) ELSE
                        coeff155 WHEN ( cur_count = to_unsigned(154, 8) ) ELSE
                        coeff156 WHEN ( cur_count = to_unsigned(155, 8) ) ELSE
                        coeff157 WHEN ( cur_count = to_unsigned(156, 8) ) ELSE
                        coeff158 WHEN ( cur_count = to_unsigned(157, 8) ) ELSE
                        coeff159 WHEN ( cur_count = to_unsigned(158, 8) ) ELSE
                        coeff160 WHEN ( cur_count = to_unsigned(159, 8) ) ELSE
                        coeff161 WHEN ( cur_count = to_unsigned(160, 8) ) ELSE
                        coeff162 WHEN ( cur_count = to_unsigned(161, 8) ) ELSE
                        coeff163 WHEN ( cur_count = to_unsigned(162, 8) ) ELSE
                        coeff164 WHEN ( cur_count = to_unsigned(163, 8) ) ELSE
                        coeff165 WHEN ( cur_count = to_unsigned(164, 8) ) ELSE
                        coeff166 WHEN ( cur_count = to_unsigned(165, 8) ) ELSE
                        coeff167 WHEN ( cur_count = to_unsigned(166, 8) ) ELSE
                        coeff168 WHEN ( cur_count = to_unsigned(167, 8) ) ELSE
                        coeff169 WHEN ( cur_count = to_unsigned(168, 8) ) ELSE
                        coeff170 WHEN ( cur_count = to_unsigned(169, 8) ) ELSE
                        coeff171 WHEN ( cur_count = to_unsigned(170, 8) ) ELSE
                        coeff172 WHEN ( cur_count = to_unsigned(171, 8) ) ELSE
                        coeff173 WHEN ( cur_count = to_unsigned(172, 8) ) ELSE
                        coeff174 WHEN ( cur_count = to_unsigned(173, 8) ) ELSE
                        coeff175 WHEN ( cur_count = to_unsigned(174, 8) ) ELSE
                        coeff176 WHEN ( cur_count = to_unsigned(175, 8) ) ELSE
                        coeff177 WHEN ( cur_count = to_unsigned(176, 8) ) ELSE
                        coeff178 WHEN ( cur_count = to_unsigned(177, 8) ) ELSE
                        coeff179 WHEN ( cur_count = to_unsigned(178, 8) ) ELSE
                        coeff180 WHEN ( cur_count = to_unsigned(179, 8) ) ELSE
                        coeff181 WHEN ( cur_count = to_unsigned(180, 8) ) ELSE
                        coeff182 WHEN ( cur_count = to_unsigned(181, 8) ) ELSE
                        coeff183 WHEN ( cur_count = to_unsigned(182, 8) ) ELSE
                        coeff184 WHEN ( cur_count = to_unsigned(183, 8) ) ELSE
                        coeff185 WHEN ( cur_count = to_unsigned(184, 8) ) ELSE
                        coeff186 WHEN ( cur_count = to_unsigned(185, 8) ) ELSE
                        coeff187 WHEN ( cur_count = to_unsigned(186, 8) ) ELSE
                        coeff188 WHEN ( cur_count = to_unsigned(187, 8) ) ELSE
                        coeff189 WHEN ( cur_count = to_unsigned(188, 8) ) ELSE
                        coeff190 WHEN ( cur_count = to_unsigned(189, 8) ) ELSE
                        coeff191 WHEN ( cur_count = to_unsigned(190, 8) ) ELSE
                        coeff192 WHEN ( cur_count = to_unsigned(191, 8) ) ELSE
                        coeff193 WHEN ( cur_count = to_unsigned(192, 8) ) ELSE
                        coeff194 WHEN ( cur_count = to_unsigned(193, 8) ) ELSE
                        coeff195 WHEN ( cur_count = to_unsigned(194, 8) ) ELSE
                        coeff196 WHEN ( cur_count = to_unsigned(195, 8) ) ELSE
                        coeff197 WHEN ( cur_count = to_unsigned(196, 8) ) ELSE
                        coeff198 WHEN ( cur_count = to_unsigned(197, 8) ) ELSE
                        coeff199 WHEN ( cur_count = to_unsigned(198, 8) ) ELSE
                        coeff200 WHEN ( cur_count = to_unsigned(199, 8) ) ELSE
                        coeff201;
  mul_temp <= inputmux_1 * signed( '0' & product_1_mux);
  product_1 <= mul_temp(31 DOWNTO 0);

  prod_typeconvert_1 <= resize(product_1, 39);

  add_temp <= resize(prod_typeconvert_1, 40) + resize(acc_out_1, 40);
  acc_sum_1 <= add_temp(38 DOWNTO 0);

  acc_in_1 <= prod_typeconvert_1 WHEN ( phase_0 = '1' ) ELSE
                   acc_sum_1;

  Acc_reg_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      acc_out_1 <= (OTHERS => '0');
    ELSIF clk'event AND clk = '1' THEN
      IF ce = '1' THEN
        acc_out_1 <= acc_in_1;
      END IF;
    END IF; 
  END PROCESS Acc_reg_1_process;

  Finalsum_reg_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      acc_final <= (OTHERS => '0');
    ELSIF clk'event AND clk = '1' THEN
      IF phase_0 = '1' THEN
        acc_final <= acc_out_1;
      END IF;
    END IF; 
  END PROCESS Finalsum_reg_process;

  output_typeconvert <= acc_final;

  Output_Register_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      output_register <= (OTHERS => '0');
    ELSIF clk'event AND clk = '1' THEN
      IF phase_200 = '1' THEN
        output_register <= output_typeconvert;
      END IF;
    END IF; 
  END PROCESS Output_Register_process;

  -- Assignment Statements
  filter_out <= std_logic_vector(output_register);
END rtl;
