-- -------------------------------------------------------------
--
-- Module: filter
-- Generated by MATLAB(R) 9.9 and Filter Design HDL Coder 3.1.8.
-- Generated on: 2021-04-16 23:24:36
-- -------------------------------------------------------------

-- -------------------------------------------------------------
-- HDL Code Generation Options:
--
-- TargetLanguage: VHDL
-- ClockEnableInputPort: ce
-- TargetDirectory: D:\TonyGit\SysGen
-- SerialPartition: 36
-- TestBenchStimulus: impulse step ramp chirp noise 

-- -------------------------------------------------------------
-- HDL Implementation    : Fully Serial
-- Folding Factor        : 36
-- -------------------------------------------------------------
-- Filter Settings:
--
-- Discrete-Time FIR Filter (real)
-- -------------------------------
-- Filter Structure  : Direct-Form FIR
-- Filter Length     : 36
-- Stable            : Yes
-- Linear Phase      : Yes (Type 2)
-- Arithmetic        : fixed
-- Numerator         : s16,19 -> [-6.250000e-02 6.250000e-02)
-- Input             : s16,15 -> [-1 1)
-- Filter Internals  : Full Precision
--   Output          : s35,34 -> [-1 1)  (auto determined)
--   Product         : s31,34 -> [-6.250000e-02 6.250000e-02)  (auto determined)
--   Accumulator     : s35,34 -> [-1 1)  (auto determined)
--   Round Mode      : No rounding
--   Overflow Mode   : No overflow
-- -------------------------------------------------------------



LIBRARY IEEE;
USE IEEE.std_logic_1164.all;
USE IEEE.numeric_std.ALL;

ENTITY filter IS
   PORT( clk                             :   IN    std_logic; 
         ce                              :   IN    std_logic; 
         reset                           :   IN    std_logic; 
         filter_in                       :   IN    std_logic_vector(15 DOWNTO 0); -- sfix16_En15
         filter_out                      :   OUT   std_logic_vector(34 DOWNTO 0)  -- sfix35_En34
         );

END filter;


----------------------------------------------------------------
--Module Architecture: filter
----------------------------------------------------------------
ARCHITECTURE rtl OF filter IS
  -- Local Functions
  -- Type Definitions
  TYPE delay_pipeline_type IS ARRAY (NATURAL range <>) OF signed(15 DOWNTO 0); -- sfix16_En15
  -- Constants
  CONSTANT coeff1                         : signed(15 DOWNTO 0) := to_signed(197, 16); -- sfix16_En19
  CONSTANT coeff2                         : signed(15 DOWNTO 0) := to_signed(428, 16); -- sfix16_En19
  CONSTANT coeff3                         : signed(15 DOWNTO 0) := to_signed(852, 16); -- sfix16_En19
  CONSTANT coeff4                         : signed(15 DOWNTO 0) := to_signed(1503, 16); -- sfix16_En19
  CONSTANT coeff5                         : signed(15 DOWNTO 0) := to_signed(2436, 16); -- sfix16_En19
  CONSTANT coeff6                         : signed(15 DOWNTO 0) := to_signed(3696, 16); -- sfix16_En19
  CONSTANT coeff7                         : signed(15 DOWNTO 0) := to_signed(5314, 16); -- sfix16_En19
  CONSTANT coeff8                         : signed(15 DOWNTO 0) := to_signed(7298, 16); -- sfix16_En19
  CONSTANT coeff9                         : signed(15 DOWNTO 0) := to_signed(9629, 16); -- sfix16_En19
  CONSTANT coeff10                        : signed(15 DOWNTO 0) := to_signed(12258, 16); -- sfix16_En19
  CONSTANT coeff11                        : signed(15 DOWNTO 0) := to_signed(15102, 16); -- sfix16_En19
  CONSTANT coeff12                        : signed(15 DOWNTO 0) := to_signed(18051, 16); -- sfix16_En19
  CONSTANT coeff13                        : signed(15 DOWNTO 0) := to_signed(20972, 16); -- sfix16_En19
  CONSTANT coeff14                        : signed(15 DOWNTO 0) := to_signed(23718, 16); -- sfix16_En19
  CONSTANT coeff15                        : signed(15 DOWNTO 0) := to_signed(26140, 16); -- sfix16_En19
  CONSTANT coeff16                        : signed(15 DOWNTO 0) := to_signed(28098, 16); -- sfix16_En19
  CONSTANT coeff17                        : signed(15 DOWNTO 0) := to_signed(29475, 16); -- sfix16_En19
  CONSTANT coeff18                        : signed(15 DOWNTO 0) := to_signed(30186, 16); -- sfix16_En19
  CONSTANT coeff19                        : signed(15 DOWNTO 0) := to_signed(30186, 16); -- sfix16_En19
  CONSTANT coeff20                        : signed(15 DOWNTO 0) := to_signed(29475, 16); -- sfix16_En19
  CONSTANT coeff21                        : signed(15 DOWNTO 0) := to_signed(28098, 16); -- sfix16_En19
  CONSTANT coeff22                        : signed(15 DOWNTO 0) := to_signed(26140, 16); -- sfix16_En19
  CONSTANT coeff23                        : signed(15 DOWNTO 0) := to_signed(23718, 16); -- sfix16_En19
  CONSTANT coeff24                        : signed(15 DOWNTO 0) := to_signed(20972, 16); -- sfix16_En19
  CONSTANT coeff25                        : signed(15 DOWNTO 0) := to_signed(18051, 16); -- sfix16_En19
  CONSTANT coeff26                        : signed(15 DOWNTO 0) := to_signed(15102, 16); -- sfix16_En19
  CONSTANT coeff27                        : signed(15 DOWNTO 0) := to_signed(12258, 16); -- sfix16_En19
  CONSTANT coeff28                        : signed(15 DOWNTO 0) := to_signed(9629, 16); -- sfix16_En19
  CONSTANT coeff29                        : signed(15 DOWNTO 0) := to_signed(7298, 16); -- sfix16_En19
  CONSTANT coeff30                        : signed(15 DOWNTO 0) := to_signed(5314, 16); -- sfix16_En19
  CONSTANT coeff31                        : signed(15 DOWNTO 0) := to_signed(3696, 16); -- sfix16_En19
  CONSTANT coeff32                        : signed(15 DOWNTO 0) := to_signed(2436, 16); -- sfix16_En19
  CONSTANT coeff33                        : signed(15 DOWNTO 0) := to_signed(1503, 16); -- sfix16_En19
  CONSTANT coeff34                        : signed(15 DOWNTO 0) := to_signed(852, 16); -- sfix16_En19
  CONSTANT coeff35                        : signed(15 DOWNTO 0) := to_signed(428, 16); -- sfix16_En19
  CONSTANT coeff36                        : signed(15 DOWNTO 0) := to_signed(197, 16); -- sfix16_En19

  -- Signals
  SIGNAL cur_count                        : unsigned(5 DOWNTO 0); -- ufix6
  SIGNAL phase_35                         : std_logic; -- boolean
  SIGNAL phase_0                          : std_logic; -- boolean
  SIGNAL delay_pipeline                   : delay_pipeline_type(0 TO 35); -- sfix16_En15
  SIGNAL inputmux_1                       : signed(15 DOWNTO 0); -- sfix16_En15
  SIGNAL acc_final                        : signed(34 DOWNTO 0); -- sfix35_En34
  SIGNAL acc_out_1                        : signed(34 DOWNTO 0); -- sfix35_En34
  SIGNAL product_1                        : signed(30 DOWNTO 0); -- sfix31_En34
  SIGNAL product_1_mux                    : signed(15 DOWNTO 0); -- sfix16_En19
  SIGNAL mul_temp                         : signed(31 DOWNTO 0); -- sfix32_En34
  SIGNAL prod_typeconvert_1               : signed(34 DOWNTO 0); -- sfix35_En34
  SIGNAL acc_sum_1                        : signed(34 DOWNTO 0); -- sfix35_En34
  SIGNAL acc_in_1                         : signed(34 DOWNTO 0); -- sfix35_En34
  SIGNAL add_temp                         : signed(35 DOWNTO 0); -- sfix36_En34
  SIGNAL output_typeconvert               : signed(34 DOWNTO 0); -- sfix35_En34
  SIGNAL output_register                  : signed(34 DOWNTO 0); -- sfix35_En34


BEGIN

  -- Block Statements
  Counter_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      cur_count <= to_unsigned(35, 6);
    ELSIF clk'event AND clk = '1' THEN
      IF ce = '1' THEN
        IF cur_count >= to_unsigned(35, 6) THEN
          cur_count <= to_unsigned(0, 6);
        ELSE
          cur_count <= cur_count + to_unsigned(1, 6);
        END IF;
      END IF;
    END IF; 
  END PROCESS Counter_process;

  phase_35 <= '1' WHEN cur_count = to_unsigned(35, 6) AND ce = '1' ELSE '0';

  phase_0 <= '1' WHEN cur_count = to_unsigned(0, 6) AND ce = '1' ELSE '0';

  Delay_Pipeline_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delay_pipeline(0 TO 35) <= (OTHERS => (OTHERS => '0'));
    ELSIF clk'event AND clk = '1' THEN
      IF phase_35 = '1' THEN
        delay_pipeline(0) <= signed(filter_in);
        delay_pipeline(1 TO 35) <= delay_pipeline(0 TO 34);
      END IF;
    END IF; 
  END PROCESS Delay_Pipeline_process;

  inputmux_1 <= delay_pipeline(0) WHEN ( cur_count = to_unsigned(0, 6) ) ELSE
                     delay_pipeline(1) WHEN ( cur_count = to_unsigned(1, 6) ) ELSE
                     delay_pipeline(2) WHEN ( cur_count = to_unsigned(2, 6) ) ELSE
                     delay_pipeline(3) WHEN ( cur_count = to_unsigned(3, 6) ) ELSE
                     delay_pipeline(4) WHEN ( cur_count = to_unsigned(4, 6) ) ELSE
                     delay_pipeline(5) WHEN ( cur_count = to_unsigned(5, 6) ) ELSE
                     delay_pipeline(6) WHEN ( cur_count = to_unsigned(6, 6) ) ELSE
                     delay_pipeline(7) WHEN ( cur_count = to_unsigned(7, 6) ) ELSE
                     delay_pipeline(8) WHEN ( cur_count = to_unsigned(8, 6) ) ELSE
                     delay_pipeline(9) WHEN ( cur_count = to_unsigned(9, 6) ) ELSE
                     delay_pipeline(10) WHEN ( cur_count = to_unsigned(10, 6) ) ELSE
                     delay_pipeline(11) WHEN ( cur_count = to_unsigned(11, 6) ) ELSE
                     delay_pipeline(12) WHEN ( cur_count = to_unsigned(12, 6) ) ELSE
                     delay_pipeline(13) WHEN ( cur_count = to_unsigned(13, 6) ) ELSE
                     delay_pipeline(14) WHEN ( cur_count = to_unsigned(14, 6) ) ELSE
                     delay_pipeline(15) WHEN ( cur_count = to_unsigned(15, 6) ) ELSE
                     delay_pipeline(16) WHEN ( cur_count = to_unsigned(16, 6) ) ELSE
                     delay_pipeline(17) WHEN ( cur_count = to_unsigned(17, 6) ) ELSE
                     delay_pipeline(18) WHEN ( cur_count = to_unsigned(18, 6) ) ELSE
                     delay_pipeline(19) WHEN ( cur_count = to_unsigned(19, 6) ) ELSE
                     delay_pipeline(20) WHEN ( cur_count = to_unsigned(20, 6) ) ELSE
                     delay_pipeline(21) WHEN ( cur_count = to_unsigned(21, 6) ) ELSE
                     delay_pipeline(22) WHEN ( cur_count = to_unsigned(22, 6) ) ELSE
                     delay_pipeline(23) WHEN ( cur_count = to_unsigned(23, 6) ) ELSE
                     delay_pipeline(24) WHEN ( cur_count = to_unsigned(24, 6) ) ELSE
                     delay_pipeline(25) WHEN ( cur_count = to_unsigned(25, 6) ) ELSE
                     delay_pipeline(26) WHEN ( cur_count = to_unsigned(26, 6) ) ELSE
                     delay_pipeline(27) WHEN ( cur_count = to_unsigned(27, 6) ) ELSE
                     delay_pipeline(28) WHEN ( cur_count = to_unsigned(28, 6) ) ELSE
                     delay_pipeline(29) WHEN ( cur_count = to_unsigned(29, 6) ) ELSE
                     delay_pipeline(30) WHEN ( cur_count = to_unsigned(30, 6) ) ELSE
                     delay_pipeline(31) WHEN ( cur_count = to_unsigned(31, 6) ) ELSE
                     delay_pipeline(32) WHEN ( cur_count = to_unsigned(32, 6) ) ELSE
                     delay_pipeline(33) WHEN ( cur_count = to_unsigned(33, 6) ) ELSE
                     delay_pipeline(34) WHEN ( cur_count = to_unsigned(34, 6) ) ELSE
                     delay_pipeline(35);

  --   ------------------ Serial partition # 1 ------------------

  product_1_mux <= coeff1 WHEN ( cur_count = to_unsigned(0, 6) ) ELSE
                        coeff2 WHEN ( cur_count = to_unsigned(1, 6) ) ELSE
                        coeff3 WHEN ( cur_count = to_unsigned(2, 6) ) ELSE
                        coeff4 WHEN ( cur_count = to_unsigned(3, 6) ) ELSE
                        coeff5 WHEN ( cur_count = to_unsigned(4, 6) ) ELSE
                        coeff6 WHEN ( cur_count = to_unsigned(5, 6) ) ELSE
                        coeff7 WHEN ( cur_count = to_unsigned(6, 6) ) ELSE
                        coeff8 WHEN ( cur_count = to_unsigned(7, 6) ) ELSE
                        coeff9 WHEN ( cur_count = to_unsigned(8, 6) ) ELSE
                        coeff10 WHEN ( cur_count = to_unsigned(9, 6) ) ELSE
                        coeff11 WHEN ( cur_count = to_unsigned(10, 6) ) ELSE
                        coeff12 WHEN ( cur_count = to_unsigned(11, 6) ) ELSE
                        coeff13 WHEN ( cur_count = to_unsigned(12, 6) ) ELSE
                        coeff14 WHEN ( cur_count = to_unsigned(13, 6) ) ELSE
                        coeff15 WHEN ( cur_count = to_unsigned(14, 6) ) ELSE
                        coeff16 WHEN ( cur_count = to_unsigned(15, 6) ) ELSE
                        coeff17 WHEN ( cur_count = to_unsigned(16, 6) ) ELSE
                        coeff18 WHEN ( cur_count = to_unsigned(17, 6) ) ELSE
                        coeff19 WHEN ( cur_count = to_unsigned(18, 6) ) ELSE
                        coeff20 WHEN ( cur_count = to_unsigned(19, 6) ) ELSE
                        coeff21 WHEN ( cur_count = to_unsigned(20, 6) ) ELSE
                        coeff22 WHEN ( cur_count = to_unsigned(21, 6) ) ELSE
                        coeff23 WHEN ( cur_count = to_unsigned(22, 6) ) ELSE
                        coeff24 WHEN ( cur_count = to_unsigned(23, 6) ) ELSE
                        coeff25 WHEN ( cur_count = to_unsigned(24, 6) ) ELSE
                        coeff26 WHEN ( cur_count = to_unsigned(25, 6) ) ELSE
                        coeff27 WHEN ( cur_count = to_unsigned(26, 6) ) ELSE
                        coeff28 WHEN ( cur_count = to_unsigned(27, 6) ) ELSE
                        coeff29 WHEN ( cur_count = to_unsigned(28, 6) ) ELSE
                        coeff30 WHEN ( cur_count = to_unsigned(29, 6) ) ELSE
                        coeff31 WHEN ( cur_count = to_unsigned(30, 6) ) ELSE
                        coeff32 WHEN ( cur_count = to_unsigned(31, 6) ) ELSE
                        coeff33 WHEN ( cur_count = to_unsigned(32, 6) ) ELSE
                        coeff34 WHEN ( cur_count = to_unsigned(33, 6) ) ELSE
                        coeff35 WHEN ( cur_count = to_unsigned(34, 6) ) ELSE
                        coeff36;
  mul_temp <= inputmux_1 * product_1_mux;
  product_1 <= mul_temp(30 DOWNTO 0);

  prod_typeconvert_1 <= resize(product_1, 35);

  add_temp <= resize(prod_typeconvert_1, 36) + resize(acc_out_1, 36);
  acc_sum_1 <= add_temp(34 DOWNTO 0);

  acc_in_1 <= prod_typeconvert_1 WHEN ( phase_0 = '1' ) ELSE
                   acc_sum_1;

  Acc_reg_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      acc_out_1 <= (OTHERS => '0');
    ELSIF clk'event AND clk = '1' THEN
      IF ce = '1' THEN
        acc_out_1 <= acc_in_1;
      END IF;
    END IF; 
  END PROCESS Acc_reg_1_process;

  Finalsum_reg_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      acc_final <= (OTHERS => '0');
    ELSIF clk'event AND clk = '1' THEN
      IF phase_0 = '1' THEN
        acc_final <= acc_out_1;
      END IF;
    END IF; 
  END PROCESS Finalsum_reg_process;

  output_typeconvert <= acc_final;

  Output_Register_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      output_register <= (OTHERS => '0');
    ELSIF clk'event AND clk = '1' THEN
      IF phase_35 = '1' THEN
        output_register <= output_typeconvert;
      END IF;
    END IF; 
  END PROCESS Output_Register_process;

  -- Assignment Statements
  filter_out <= std_logic_vector(output_register);
END rtl;
